"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.secret_api import SecretApi  # noqa: E501


class TestSecretApi(unittest.TestCase):
    """SecretApi unit test stubs"""

    def setUp(self):
        self.api = SecretApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_secret(self):
        """Test case for create_secret

        Create a secret  # noqa: E501
        """
        pass

    def test_delete_secret_by_id(self):
        """Test case for delete_secret_by_id

        Delete a secret by an id  # noqa: E501
        """
        pass

    def test_find_secret_by_id(self):
        """Test case for find_secret_by_id

        Find secret by Id  # noqa: E501
        """
        pass

    def test_find_secret_data_by_id(self):
        """Test case for find_secret_data_by_id

        Find secret data by Id  # noqa: E501
        """
        pass

    def test_find_secrets(self):
        """Test case for find_secrets

        Retrieve all secrets  # noqa: E501
        """
        pass

    def test_update_secret(self):
        """Test case for update_secret

        Update a secret  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
