"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.data_warehouse import DataWarehouse
from graalsystems.model.data_warehouse_page_all_of import DataWarehousePageAllOf
from graalsystems.model.page import Page
globals()['DataWarehouse'] = DataWarehouse
globals()['DataWarehousePageAllOf'] = DataWarehousePageAllOf
globals()['Page'] = Page
from graalsystems.model.data_warehouse_page import DataWarehousePage


class TestDataWarehousePage(unittest.TestCase):
    """DataWarehousePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataWarehousePage(self):
        """Test DataWarehousePage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataWarehousePage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
