"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.estimation_api import EstimationApi  # noqa: E501


class TestEstimationApi(unittest.TestCase):
    """EstimationApi unit test stubs"""

    def setUp(self):
        self.api = EstimationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_estimation(self):
        """Test case for create_estimation

        Create an estimation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
