"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.role import Role
from graalsystems.model.role_assignment import RoleAssignment
globals()['Role'] = Role
globals()['RoleAssignment'] = RoleAssignment
from graalsystems.model.role_and_assignment import RoleAndAssignment


class TestRoleAndAssignment(unittest.TestCase):
    """RoleAndAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleAndAssignment(self):
        """Test RoleAndAssignment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleAndAssignment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
