"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.sessions_api import SessionsApi  # noqa: E501


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self):
        self.api = SessionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_notebook(self):
        """Test case for create_notebook

        Check if the workspace is running and create a notebook  # noqa: E501
        """
        pass

    def test_create_session(self):
        """Test case for create_session

        Create a new workspace and corresponding session  # noqa: E501
        """
        pass

    def test_delete_session(self):
        """Test case for delete_session

        Delete a session  # noqa: E501
        """
        pass

    def test_get_sessions(self):
        """Test case for get_sessions

        Get existing Sessions, used for live-coding.  # noqa: E501
        """
        pass

    def test_run_session(self):
        """Test case for run_session

        Run a session  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
