"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.library import Library
globals()['Library'] = Library
from graalsystems.model.knime_options_all_of import KnimeOptionsAllOf


class TestKnimeOptionsAllOf(unittest.TestCase):
    """KnimeOptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKnimeOptionsAllOf(self):
        """Test KnimeOptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KnimeOptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
