"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.project1_all_of import Project1AllOf
from graalsystems.model.resource import Resource
globals()['Project1AllOf'] = Project1AllOf
globals()['Resource'] = Resource
from graalsystems.model.project1 import Project1


class TestProject1(unittest.TestCase):
    """Project1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProject1(self):
        """Test Project1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Project1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
