"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.cron_schedule import CronSchedule
from graalsystems.model.cron_schedule_all_of import CronScheduleAllOf
from graalsystems.model.run_once_schedule import RunOnceSchedule
from graalsystems.model.schedule import Schedule
globals()['CronSchedule'] = CronSchedule
globals()['CronScheduleAllOf'] = CronScheduleAllOf
globals()['RunOnceSchedule'] = RunOnceSchedule
globals()['Schedule'] = Schedule
from graalsystems.model.cron_schedule import CronSchedule


class TestCronSchedule(unittest.TestCase):
    """CronSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCronSchedule(self):
        """Test CronSchedule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CronSchedule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
