"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a user  # noqa: E501
        """
        pass

    def test_delete_user_by_id(self):
        """Test case for delete_user_by_id

        Delete a user by an id  # noqa: E501
        """
        pass

    def test_find_current_user(self):
        """Test case for find_current_user

        Just... me  # noqa: E501
        """
        pass

    def test_find_logs_by_user_id(self):
        """Test case for find_logs_by_user_id

        Find logs by a user id  # noqa: E501
        """
        pass

    def test_find_roles_by_user_id(self):
        """Test case for find_roles_by_user_id

        Find roles by a user id  # noqa: E501
        """
        pass

    def test_find_user_by_id(self):
        """Test case for find_user_by_id

        Find user by Id  # noqa: E501
        """
        pass

    def test_find_user_by_remote_user_id(self):
        """Test case for find_user_by_remote_user_id

        Find user by remote user id  # noqa: E501
        """
        pass

    def test_find_users(self):
        """Test case for find_users

        Retrieve all users  # noqa: E501
        """
        pass

    def test_get_audit_logs(self):
        """Test case for get_audit_logs

        Find logs  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
