"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.quota_api import QuotaApi  # noqa: E501


class TestQuotaApi(unittest.TestCase):
    """QuotaApi unit test stubs"""

    def setUp(self):
        self.api = QuotaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_quota_by_key(self):
        """Test case for find_quota_by_key

        Find quota by key  # noqa: E501
        """
        pass

    def test_find_quotas(self):
        """Test case for find_quotas

        Retrieve all quotas  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
