"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.layer_api import LayerApi  # noqa: E501


class TestLayerApi(unittest.TestCase):
    """LayerApi unit test stubs"""

    def setUp(self):
        self.api = LayerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_layer(self):
        """Test case for create_layer

        Create a layer  # noqa: E501
        """
        pass

    def test_delete_layer_by_id(self):
        """Test case for delete_layer_by_id

        Delete a layer by an id  # noqa: E501
        """
        pass

    def test_find_layer_by_id(self):
        """Test case for find_layer_by_id

        Find layer by Id  # noqa: E501
        """
        pass

    def test_find_layers(self):
        """Test case for find_layers

        Retrieve all layers  # noqa: E501
        """
        pass

    def test_update_layer(self):
        """Test case for update_layer

        Update a layer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
