"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.azure_log_analytics_notification_all_of import AzureLogAnalyticsNotificationAllOf


class TestAzureLogAnalyticsNotificationAllOf(unittest.TestCase):
    """AzureLogAnalyticsNotificationAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureLogAnalyticsNotificationAllOf(self):
        """Test AzureLogAnalyticsNotificationAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AzureLogAnalyticsNotificationAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
