"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.activity import Activity
from graalsystems.model.reaction import Reaction
from graalsystems.model.user1 import User1
from graalsystems.model.workflow1 import Workflow1
from graalsystems.model.workflow_activity_all_of import WorkflowActivityAllOf
globals()['Activity'] = Activity
globals()['Reaction'] = Reaction
globals()['User1'] = User1
globals()['Workflow1'] = Workflow1
globals()['WorkflowActivityAllOf'] = WorkflowActivityAllOf
from graalsystems.model.workflow_activity import WorkflowActivity


class TestWorkflowActivity(unittest.TestCase):
    """WorkflowActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowActivity(self):
        """Test WorkflowActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
