"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.price_api import PriceApi  # noqa: E501


class TestPriceApi(unittest.TestCase):
    """PriceApi unit test stubs"""

    def setUp(self):
        self.api = PriceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_price(self):
        """Test case for create_price

        Create an price  # noqa: E501
        """
        pass

    def test_delete_price_by_id(self):
        """Test case for delete_price_by_id

        Delete a price by its id  # noqa: E501
        """
        pass

    def test_find_price_by_id(self):
        """Test case for find_price_by_id

        Find price by Id  # noqa: E501
        """
        pass

    def test_find_prices(self):
        """Test case for find_prices

        Retrieve all prices  # noqa: E501
        """
        pass

    def test_update_price(self):
        """Test case for update_price

        Update a price  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
