"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.follow_api import FollowApi  # noqa: E501


class TestFollowApi(unittest.TestCase):
    """FollowApi unit test stubs"""

    def setUp(self):
        self.api = FollowApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_catalog_follower(self):
        """Test case for create_catalog_follower

        Create Catalog Followers  # noqa: E501
        """
        pass

    def test_create_database_follower(self):
        """Test case for create_database_follower

        Create Database Followers  # noqa: E501
        """
        pass

    def test_create_job_follower(self):
        """Test case for create_job_follower

        Create Job Followers  # noqa: E501
        """
        pass

    def test_create_project_follower(self):
        """Test case for create_project_follower

        Create Project Followers  # noqa: E501
        """
        pass

    def test_create_table_follower(self):
        """Test case for create_table_follower

        Create Table Followers  # noqa: E501
        """
        pass

    def test_create_user_follower(self):
        """Test case for create_user_follower

        Create User Followers  # noqa: E501
        """
        pass

    def test_create_workflow_follower(self):
        """Test case for create_workflow_follower

        Create Workflow Followers  # noqa: E501
        """
        pass

    def test_delete_following_catalog(self):
        """Test case for delete_following_catalog

        Delete Following Catalog  # noqa: E501
        """
        pass

    def test_delete_following_database(self):
        """Test case for delete_following_database

        Delete Following Database  # noqa: E501
        """
        pass

    def test_delete_following_job(self):
        """Test case for delete_following_job

        Delete Following Job  # noqa: E501
        """
        pass

    def test_delete_following_project(self):
        """Test case for delete_following_project

        Delete Following Project  # noqa: E501
        """
        pass

    def test_delete_following_table(self):
        """Test case for delete_following_table

        Delete Following Table  # noqa: E501
        """
        pass

    def test_delete_following_user(self):
        """Test case for delete_following_user

        Delete Following User  # noqa: E501
        """
        pass

    def test_delete_following_workflow(self):
        """Test case for delete_following_workflow

        Delete Following User  # noqa: E501
        """
        pass

    def test_get_catalog_followers(self):
        """Test case for get_catalog_followers

        Get Catalog Followers  # noqa: E501
        """
        pass

    def test_get_database_followers(self):
        """Test case for get_database_followers

        Get Database Followers  # noqa: E501
        """
        pass

    def test_get_job_followers(self):
        """Test case for get_job_followers

        Get Job Followers  # noqa: E501
        """
        pass

    def test_get_project_followers(self):
        """Test case for get_project_followers

        Get Project Followers  # noqa: E501
        """
        pass

    def test_get_table_followers(self):
        """Test case for get_table_followers

        Get Table Followers  # noqa: E501
        """
        pass

    def test_get_user_followers(self):
        """Test case for get_user_followers

        Get User Followers  # noqa: E501
        """
        pass

    def test_get_user_following(self):
        """Test case for get_user_following

        Get User Following  # noqa: E501
        """
        pass

    def test_get_workflow_followers(self):
        """Test case for get_workflow_followers

        Get Workflow Followers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
