"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.less_or_equal_than_filter import LessOrEqualThanFilter


class TestLessOrEqualThanFilter(unittest.TestCase):
    """LessOrEqualThanFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLessOrEqualThanFilter(self):
        """Test LessOrEqualThanFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LessOrEqualThanFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
