"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.uri import Uri
globals()['Uri'] = Uri
from graalsystems.model.bucket import Bucket


class TestBucket(unittest.TestCase):
    """Bucket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBucket(self):
        """Test Bucket"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Bucket()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
