"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.project1 import Project1
globals()['Project1'] = Project1
from graalsystems.model.workflow1_all_of import Workflow1AllOf


class TestWorkflow1AllOf(unittest.TestCase):
    """Workflow1AllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflow1AllOf(self):
        """Test Workflow1AllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Workflow1AllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
