"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.s3_connector_options import S3ConnectorOptions


class TestS3ConnectorOptions(unittest.TestCase):
    """S3ConnectorOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3ConnectorOptions(self):
        """Test S3ConnectorOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = S3ConnectorOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
