"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.permission_api import PermissionApi  # noqa: E501


class TestPermissionApi(unittest.TestCase):
    """PermissionApi unit test stubs"""

    def setUp(self):
        self.api = PermissionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_permissions(self):
        """Test case for find_permissions

        Retrieve permissions for a specific principal  # noqa: E501
        """
        pass

    def test_has_permission(self):
        """Test case for has_permission

        Retrieve permissions for a specific principal  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
