"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.notifications import Notifications
from graalsystems.model.schedule import Schedule
from graalsystems.model.task import Task
globals()['Notifications'] = Notifications
globals()['Schedule'] = Schedule
globals()['Task'] = Task
from graalsystems.model.workflow import Workflow


class TestWorkflow(unittest.TestCase):
    """Workflow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflow(self):
        """Test Workflow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Workflow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
