"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.project1_all_of import Project1AllOf


class TestProject1AllOf(unittest.TestCase):
    """Project1AllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProject1AllOf(self):
        """Test Project1AllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Project1AllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
