"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.model_api import ModelApi  # noqa: E501


class TestModelApi(unittest.TestCase):
    """ModelApi unit test stubs"""

    def setUp(self):
        self.api = ModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_model(self):
        """Test case for create_model

        Create a model  # noqa: E501
        """
        pass

    def test_delete_model_by_id(self):
        """Test case for delete_model_by_id

        Delete a model by an id  # noqa: E501
        """
        pass

    def test_delete_model_version_by_id(self):
        """Test case for delete_model_version_by_id

        Delete a model by an id  # noqa: E501
        """
        pass

    def test_download_model(self):
        """Test case for download_model

        Download model by Id  # noqa: E501
        """
        pass

    def test_find_model_by_id(self):
        """Test case for find_model_by_id

        Find model by Id  # noqa: E501
        """
        pass

    def test_find_model_version_metadata(self):
        """Test case for find_model_version_metadata

        Get model metadata by Id  # noqa: E501
        """
        pass

    def test_find_models(self):
        """Test case for find_models

        Retrieve all models  # noqa: E501
        """
        pass

    def test_find_versions_for_model(self):
        """Test case for find_versions_for_model

        Retrieve all versions for a model  # noqa: E501
        """
        pass

    def test_update_model(self):
        """Test case for update_model

        Update a model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
