"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.user1 import User1
from graalsystems.model.workflow1 import Workflow1
globals()['User1'] = User1
globals()['Workflow1'] = Workflow1
from graalsystems.model.workflow_activity_all_of import WorkflowActivityAllOf


class TestWorkflowActivityAllOf(unittest.TestCase):
    """WorkflowActivityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowActivityAllOf(self):
        """Test WorkflowActivityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowActivityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
