"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.random_forest import RandomForest


class TestRandomForest(unittest.TestCase):
    """RandomForest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRandomForest(self):
        """Test RandomForest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RandomForest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
