"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.subscription_api import SubscriptionApi  # noqa: E501


class TestSubscriptionApi(unittest.TestCase):
    """SubscriptionApi unit test stubs"""

    def setUp(self):
        self.api = SubscriptionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_subscription(self):
        """Test case for create_subscription

        Create an subscription  # noqa: E501
        """
        pass

    def test_delete_subscription_by_id(self):
        """Test case for delete_subscription_by_id

        Delete a subscription by its id  # noqa: E501
        """
        pass

    def test_find_subscription(self):
        """Test case for find_subscription

        Retrieve all subscription  # noqa: E501
        """
        pass

    def test_find_subscription_by_id(self):
        """Test case for find_subscription_by_id

        Find subscription by Id  # noqa: E501
        """
        pass

    def test_update_subscription(self):
        """Test case for update_subscription

        Update a subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
