"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.credit_card_details import CreditCardDetails
from graalsystems.model.details1 import Details1
from graalsystems.model.in_person_details import InPersonDetails
from graalsystems.model.sepa_details import SepaDetails
from graalsystems.model.sepa_details_all_of import SepaDetailsAllOf
from graalsystems.model.trial_details import TrialDetails
globals()['CreditCardDetails'] = CreditCardDetails
globals()['Details1'] = Details1
globals()['InPersonDetails'] = InPersonDetails
globals()['SepaDetails'] = SepaDetails
globals()['SepaDetailsAllOf'] = SepaDetailsAllOf
globals()['TrialDetails'] = TrialDetails
from graalsystems.model.sepa_details import SepaDetails


class TestSepaDetails(unittest.TestCase):
    """SepaDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSepaDetails(self):
        """Test SepaDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SepaDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
