"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.notification import Notification
globals()['Notification'] = Notification
from graalsystems.model.notifications import Notifications


class TestNotifications(unittest.TestCase):
    """Notifications unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotifications(self):
        """Test Notifications"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Notifications()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
