"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.identity import Identity
from graalsystems.model.user import User
globals()['Identity'] = Identity
globals()['User'] = User
from graalsystems.model.principal import Principal


class TestPrincipal(unittest.TestCase):
    """Principal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrincipal(self):
        """Test Principal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Principal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
