"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.model_version import ModelVersion


class TestModelVersion(unittest.TestCase):
    """ModelVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelVersion(self):
        """Test ModelVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
