"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.etl_dag_visitors_enums_language_type import EtlDagVisitorsEnumsLanguageType


class TestEtlDagVisitorsEnumsLanguageType(unittest.TestCase):
    """EtlDagVisitorsEnumsLanguageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEtlDagVisitorsEnumsLanguageType(self):
        """Test EtlDagVisitorsEnumsLanguageType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EtlDagVisitorsEnumsLanguageType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
