"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.enrollment_api import EnrollmentApi  # noqa: E501


class TestEnrollmentApi(unittest.TestCase):
    """EnrollmentApi unit test stubs"""

    def setUp(self):
        self.api = EnrollmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_enrollment(self):
        """Test case for create_enrollment

        Create enrollment  # noqa: E501
        """
        pass

    def test_delete_enrollment_by_id(self):
        """Test case for delete_enrollment_by_id

        Delete a enrollment by an id  # noqa: E501
        """
        pass

    def test_find_enrollment_by_enrollment_id(self):
        """Test case for find_enrollment_by_enrollment_id

        Find enrollment by Id  # noqa: E501
        """
        pass

    def test_find_enrollments(self):
        """Test case for find_enrollments

        Retrieve all enrollment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
