"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.instance_type import InstanceType


class TestInstanceType(unittest.TestCase):
    """InstanceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceType(self):
        """Test InstanceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
