"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.comment_activity import CommentActivity


class TestCommentActivity(unittest.TestCase):
    """CommentActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommentActivity(self):
        """Test CommentActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommentActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
