"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.quota_details_all_of import QuotaDetailsAllOf


class TestQuotaDetailsAllOf(unittest.TestCase):
    """QuotaDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuotaDetailsAllOf(self):
        """Test QuotaDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QuotaDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
