"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.low_code_options_all_of import LowCodeOptionsAllOf


class TestLowCodeOptionsAllOf(unittest.TestCase):
    """LowCodeOptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLowCodeOptionsAllOf(self):
        """Test LowCodeOptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LowCodeOptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
