"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.distinct_task import DistinctTask


class TestDistinctTask(unittest.TestCase):
    """DistinctTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistinctTask(self):
        """Test DistinctTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DistinctTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
