"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.admin_target import AdminTarget
from graalsystems.model.admin_target_all_of import AdminTargetAllOf
from graalsystems.model.kubernetes_target import KubernetesTarget
from graalsystems.model.target import Target
globals()['AdminTarget'] = AdminTarget
globals()['AdminTargetAllOf'] = AdminTargetAllOf
globals()['KubernetesTarget'] = KubernetesTarget
globals()['Target'] = Target
from graalsystems.model.admin_target import AdminTarget


class TestAdminTarget(unittest.TestCase):
    """AdminTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdminTarget(self):
        """Test AdminTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdminTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
