"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.instance_type_api import InstanceTypeApi  # noqa: E501


class TestInstanceTypeApi(unittest.TestCase):
    """InstanceTypeApi unit test stubs"""

    def setUp(self):
        self.api = InstanceTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_instance_type_by_instance_type_id(self):
        """Test case for find_instance_type_by_instance_type_id

        Find instance type by Id  # noqa: E501
        """
        pass

    def test_find_instance_types(self):
        """Test case for find_instance_types

        Retrieve all instance types  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
