"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.activity_api import ActivityApi  # noqa: E501


class TestActivityApi(unittest.TestCase):
    """ActivityApi unit test stubs"""

    def setUp(self):
        self.api = ActivityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_activity(self):
        """Test case for create_activity

        Create a new activity  # noqa: E501
        """
        pass

    def test_create_comment_for_activity(self):
        """Test case for create_comment_for_activity

        Insert a user comment for a given activity  # noqa: E501
        """
        pass

    def test_create_reaction_for_activity(self):
        """Test case for create_reaction_for_activity

        Insert the reaction of an user to a given activity  # noqa: E501
        """
        pass

    def test_delete_comment_from_activity(self):
        """Test case for delete_comment_from_activity

        Delete the comment of an user for a given activity  # noqa: E501
        """
        pass

    def test_delete_reaction_from_activity(self):
        """Test case for delete_reaction_from_activity

        Delete users' reactions for a given activity  # noqa: E501
        """
        pass

    def test_get_activities_from_timeline(self):
        """Test case for get_activities_from_timeline

        Get all activities from timeline  # noqa: E501
        """
        pass

    def test_get_comments_from_activity(self):
        """Test case for get_comments_from_activity

        Get all the comments for a given activity  # noqa: E501
        """
        pass

    def test_get_reactions_from_activity(self):
        """Test case for get_reactions_from_activity

        Get all user reactions for a given activity  # noqa: E501
        """
        pass

    def test_update_comment_for_activity(self):
        """Test case for update_comment_for_activity

        Update the comment of an user for a given activity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
