"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.issue_details import IssueDetails
from graalsystems.model.quota_details import QuotaDetails
from graalsystems.model.subscription_details import SubscriptionDetails
globals()['IssueDetails'] = IssueDetails
globals()['QuotaDetails'] = QuotaDetails
globals()['SubscriptionDetails'] = SubscriptionDetails
from graalsystems.model.details import Details


class TestDetails(unittest.TestCase):
    """Details unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetails(self):
        """Test Details"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Details()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
