"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.run_api import RunApi  # noqa: E501


class TestRunApi(unittest.TestCase):
    """RunApi unit test stubs"""

    def setUp(self):
        self.api = RunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_run_for_job(self):
        """Test case for create_run_for_job

        Create a run for a job  # noqa: E501
        """
        pass

    def test_create_run_for_workflow(self):
        """Test case for create_run_for_workflow

        Create a run for a workflow  # noqa: E501
        """
        pass

    def test_delete_run_by_job_id_and_run_id(self):
        """Test case for delete_run_by_job_id_and_run_id

        Delete a run by a jobId and a runId  # noqa: E501
        """
        pass

    def test_delete_run_by_workflow_id_and_run_id(self):
        """Test case for delete_run_by_workflow_id_and_run_id

        Delete a run by a workflowId and a runId  # noqa: E501
        """
        pass

    def test_find_latest_runs(self):
        """Test case for find_latest_runs

        Find the latest runs  # noqa: E501
        """
        pass

    def test_find_run_by_job_id_and_run_id(self):
        """Test case for find_run_by_job_id_and_run_id

        Find the run by a jobId and a runId  # noqa: E501
        """
        pass

    def test_find_runs_by_job_id(self):
        """Test case for find_runs_by_job_id

        Find the runs for a job  # noqa: E501
        """
        pass

    def test_find_runs_by_workflow_id(self):
        """Test case for find_runs_by_workflow_id

        Find the runs for a workflow  # noqa: E501
        """
        pass

    def test_get_file(self):
        """Test case for get_file

        Get file  # noqa: E501
        """
        pass

    def test_get_logs(self):
        """Test case for get_logs

        Get logs  # noqa: E501
        """
        pass

    def test_get_metrics_for_run(self):
        """Test case for get_metrics_for_run

        Find the metrics for a run  # noqa: E501
        """
        pass

    def test_get_run_files(self):
        """Test case for get_run_files

        Get files  # noqa: E501
        """
        pass

    def test_update_run(self):
        """Test case for update_run

        Update a run  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
