"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.dag_unverified import DagUnverified


class TestDagUnverified(unittest.TestCase):
    """DagUnverified unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDagUnverified(self):
        """Test DagUnverified"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DagUnverified()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
