"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.graph import Graph
globals()['Graph'] = Graph
from graalsystems.model.graph_page_all_of import GraphPageAllOf


class TestGraphPageAllOf(unittest.TestCase):
    """GraphPageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGraphPageAllOf(self):
        """Test GraphPageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GraphPageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
