"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.library import Library
from graalsystems.model.notifications import Notifications
from graalsystems.model.options import Options
from graalsystems.model.schedule import Schedule
globals()['Library'] = Library
globals()['Notifications'] = Notifications
globals()['Options'] = Options
globals()['Schedule'] = Schedule
from graalsystems.model.job import Job


class TestJob(unittest.TestCase):
    """Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJob(self):
        """Test Job"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Job()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
