"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.change import Change
globals()['Change'] = Change
from graalsystems.model.change_page_all_of import ChangePageAllOf


class TestChangePageAllOf(unittest.TestCase):
    """ChangePageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangePageAllOf(self):
        """Test ChangePageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangePageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
