"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.in_person_details_all_of import InPersonDetailsAllOf


class TestInPersonDetailsAllOf(unittest.TestCase):
    """InPersonDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInPersonDetailsAllOf(self):
        """Test InPersonDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InPersonDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
