"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.greater_or_equal_than_filter import GreaterOrEqualThanFilter


class TestGreaterOrEqualThanFilter(unittest.TestCase):
    """GreaterOrEqualThanFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGreaterOrEqualThanFilter(self):
        """Test GreaterOrEqualThanFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GreaterOrEqualThanFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
