"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.firewall_api import FirewallApi  # noqa: E501


class TestFirewallApi(unittest.TestCase):
    """FirewallApi unit test stubs"""

    def setUp(self):
        self.api = FirewallApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_access_by_ip(self):
        """Test case for check_access_by_ip

        check access for firewall  # noqa: E501
        """
        pass

    def test_delete_firewall_rule_by_id(self):
        """Test case for delete_firewall_rule_by_id

        Delete a rule by its id  # noqa: E501
        """
        pass

    def test_find_firewall_rule_by_firewall_rule_id(self):
        """Test case for find_firewall_rule_by_firewall_rule_id

        Find rule by Id  # noqa: E501
        """
        pass

    def test_find_firewall_rules(self):
        """Test case for find_firewall_rules

        Retrieve all firewall rules  # noqa: E501
        """
        pass

    def test_update_firewall_rule(self):
        """Test case for update_firewall_rule

        Update a rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
