"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.principal import Principal
from graalsystems.model.role import Role
from graalsystems.model.role_assignment import RoleAssignment
globals()['Principal'] = Principal
globals()['Role'] = Role
globals()['RoleAssignment'] = RoleAssignment
from graalsystems.model.role_and_principal_and_assignment import RoleAndPrincipalAndAssignment


class TestRoleAndPrincipalAndAssignment(unittest.TestCase):
    """RoleAndPrincipalAndAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleAndPrincipalAndAssignment(self):
        """Test RoleAndPrincipalAndAssignment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleAndPrincipalAndAssignment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
