"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.cron_schedule import CronSchedule
from graalsystems.model.run_once_schedule import RunOnceSchedule
from graalsystems.model.run_once_schedule_all_of import RunOnceScheduleAllOf
from graalsystems.model.schedule import Schedule
globals()['CronSchedule'] = CronSchedule
globals()['RunOnceSchedule'] = RunOnceSchedule
globals()['RunOnceScheduleAllOf'] = RunOnceScheduleAllOf
globals()['Schedule'] = Schedule
from graalsystems.model.run_once_schedule import RunOnceSchedule


class TestRunOnceSchedule(unittest.TestCase):
    """RunOnceSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunOnceSchedule(self):
        """Test RunOnceSchedule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunOnceSchedule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
