"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.endpoint_api import EndpointApi  # noqa: E501


class TestEndpointApi(unittest.TestCase):
    """EndpointApi unit test stubs"""

    def setUp(self):
        self.api = EndpointApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_call_proxy_infer(self):
        """Test case for call_proxy_infer

        Call proxy infer  # noqa: E501
        """
        pass

    def test_call_proxy_metadata(self):
        """Test case for call_proxy_metadata

        Call proxy metadata  # noqa: E501
        """
        pass

    def test_create_endpoint_for_project(self):
        """Test case for create_endpoint_for_project

        Create endpoint  # noqa: E501
        """
        pass

    def test_delete_endpoint_by_id_and_project_id(self):
        """Test case for delete_endpoint_by_id_and_project_id

        Delete an endpoint by an id  # noqa: E501
        """
        pass

    def test_find_endpoint_by_id_and_project_id(self):
        """Test case for find_endpoint_by_id_and_project_id

        Find endpoint by Id  # noqa: E501
        """
        pass

    def test_find_endpoints_by_project_id(self):
        """Test case for find_endpoints_by_project_id

        Retrieve all endpoints  # noqa: E501
        """
        pass

    def test_get_logs_for_endpoint(self):
        """Test case for get_logs_for_endpoint

        Get logs  # noqa: E501
        """
        pass

    def test_update_endpoint_by_id_and_project_id(self):
        """Test case for update_endpoint_by_id_and_project_id

        Update an endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
