"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.blob_metadata import BlobMetadata
globals()['BlobMetadata'] = BlobMetadata
from graalsystems.model.file_or_directory import FileOrDirectory


class TestFileOrDirectory(unittest.TestCase):
    """FileOrDirectory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileOrDirectory(self):
        """Test FileOrDirectory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileOrDirectory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
