"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.project1 import Project1
from graalsystems.model.user1 import User1
globals()['Project1'] = Project1
globals()['User1'] = User1
from graalsystems.model.project_activity_all_of import ProjectActivityAllOf


class TestProjectActivityAllOf(unittest.TestCase):
    """ProjectActivityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectActivityAllOf(self):
        """Test ProjectActivityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectActivityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
