"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.identity_provider_api import IdentityProviderApi  # noqa: E501


class TestIdentityProviderApi(unittest.TestCase):
    """IdentityProviderApi unit test stubs"""

    def setUp(self):
        self.api = IdentityProviderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_identity_provider(self):
        """Test case for create_identity_provider

        Create a user  # noqa: E501
        """
        pass

    def test_delete_identity_provider_by_id(self):
        """Test case for delete_identity_provider_by_id

        Delete a user by an id  # noqa: E501
        """
        pass

    def test_find_identity_provider_by_id(self):
        """Test case for find_identity_provider_by_id

        Find user by Id  # noqa: E501
        """
        pass

    def test_find_identity_providers(self):
        """Test case for find_identity_providers

        Retrieve all identity providers  # noqa: E501
        """
        pass

    def test_update_identity_provider(self):
        """Test case for update_identity_provider

        Update a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
