"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.db2_options_all_of import DB2OptionsAllOf


class TestDB2OptionsAllOf(unittest.TestCase):
    """DB2OptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDB2OptionsAllOf(self):
        """Test DB2OptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DB2OptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
