"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.payment_api import PaymentApi  # noqa: E501


class TestPaymentApi(unittest.TestCase):
    """PaymentApi unit test stubs"""

    def setUp(self):
        self.api = PaymentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_payments(self):
        """Test case for find_payments

        Retrieve all payments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
