"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.tasks_api import TasksApi  # noqa: E501


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apply_task(self):
        """Test case for apply_task

        Do task  # noqa: E501
        """
        pass

    def test_find_tasks(self):
        """Test case for find_tasks

        Get Tasks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
