"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.write_sql_params import WriteSQLParams


class TestWriteSQLParams(unittest.TestCase):
    """WriteSQLParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWriteSQLParams(self):
        """Test WriteSQLParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WriteSQLParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
