"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.page import Page
from graalsystems.model.workflow import Workflow
from graalsystems.model.workflow_page_all_of import WorkflowPageAllOf
globals()['Page'] = Page
globals()['Workflow'] = Workflow
globals()['WorkflowPageAllOf'] = WorkflowPageAllOf
from graalsystems.model.workflow_page import WorkflowPage


class TestWorkflowPage(unittest.TestCase):
    """WorkflowPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowPage(self):
        """Test WorkflowPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
