"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.details1 import Details1
globals()['Details1'] = Details1
from graalsystems.model.payment_method import PaymentMethod


class TestPaymentMethod(unittest.TestCase):
    """PaymentMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentMethod(self):
        """Test PaymentMethod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentMethod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
