"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.dag import Dag
from graalsystems.model.etl_dag_schemas_enums_language_type import EtlDagSchemasEnumsLanguageType
globals()['Dag'] = Dag
globals()['EtlDagSchemasEnumsLanguageType'] = EtlDagSchemasEnumsLanguageType
from graalsystems.model.code_action import CodeAction


class TestCodeAction(unittest.TestCase):
    """CodeAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodeAction(self):
        """Test CodeAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodeAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
