"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.datawarehouse_api import DatawarehouseApi  # noqa: E501


class TestDatawarehouseApi(unittest.TestCase):
    """DatawarehouseApi unit test stubs"""

    def setUp(self):
        self.api = DatawarehouseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_data_warehouse(self):
        """Test case for create_data_warehouse

        Create datawarehouse  # noqa: E501
        """
        pass

    def test_delete_data_warehouse_by_id(self):
        """Test case for delete_data_warehouse_by_id

        Delete a datawarehouse by an id  # noqa: E501
        """
        pass

    def test_find_changes(self):
        """Test case for find_changes

        Find changes by datawarehouse id  # noqa: E501
        """
        pass

    def test_find_data_warehouse_by_id(self):
        """Test case for find_data_warehouse_by_id

        Find datawarehouse by Id  # noqa: E501
        """
        pass

    def test_find_data_warehouses(self):
        """Test case for find_data_warehouses

        Retrieve all datawarehouses  # noqa: E501
        """
        pass

    def test_find_tables(self):
        """Test case for find_tables

        Find tables by datawarehouse id  # noqa: E501
        """
        pass

    def test_get_logs_for_datawarehouse(self):
        """Test case for get_logs_for_datawarehouse

        Get logs  # noqa: E501
        """
        pass

    def test_update_data_warehouse(self):
        """Test case for update_data_warehouse

        Update a datawarehouse  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
