"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.cron_schedule import CronSchedule
from graalsystems.model.run_once_schedule import RunOnceSchedule
globals()['CronSchedule'] = CronSchedule
globals()['RunOnceSchedule'] = RunOnceSchedule
from graalsystems.model.schedule import Schedule


class TestSchedule(unittest.TestCase):
    """Schedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchedule(self):
        """Test Schedule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Schedule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
