"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.invoice_api import InvoiceApi  # noqa: E501


class TestInvoiceApi(unittest.TestCase):
    """InvoiceApi unit test stubs"""

    def setUp(self):
        self.api = InvoiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_invoice(self):
        """Test case for create_invoice

        Create an invoice  # noqa: E501
        """
        pass

    def test_delete_invoice_by_id(self):
        """Test case for delete_invoice_by_id

        Delete a invoice by its id  # noqa: E501
        """
        pass

    def test_download_invoice_by_id(self):
        """Test case for download_invoice_by_id

        Download invoice by Id  # noqa: E501
        """
        pass

    def test_find_invoice_by_id(self):
        """Test case for find_invoice_by_id

        Find invoice by Id  # noqa: E501
        """
        pass

    def test_find_invoices(self):
        """Test case for find_invoices

        Retrieve all invoices  # noqa: E501
        """
        pass

    def test_update_invoice(self):
        """Test case for update_invoice

        Update a invoice  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
