"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.read_task import ReadTask


class TestReadTask(unittest.TestCase):
    """ReadTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadTask(self):
        """Test ReadTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReadTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
