"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.project1 import Project1
globals()['Project1'] = Project1
from graalsystems.model.job1_all_of import Job1AllOf


class TestJob1AllOf(unittest.TestCase):
    """Job1AllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJob1AllOf(self):
        """Test Job1AllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Job1AllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
