"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.local_connector import LocalConnector


class TestLocalConnector(unittest.TestCase):
    """LocalConnector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalConnector(self):
        """Test LocalConnector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocalConnector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
