"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.endpoint import Endpoint
globals()['Endpoint'] = Endpoint
from graalsystems.model.endpoint_page_all_of import EndpointPageAllOf


class TestEndpointPageAllOf(unittest.TestCase):
    """EndpointPageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointPageAllOf(self):
        """Test EndpointPageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EndpointPageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
