"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.credit_card_details import CreditCardDetails
from graalsystems.model.in_person_details import InPersonDetails
from graalsystems.model.sepa_details import SepaDetails
from graalsystems.model.trial_details import TrialDetails
globals()['CreditCardDetails'] = CreditCardDetails
globals()['InPersonDetails'] = InPersonDetails
globals()['SepaDetails'] = SepaDetails
globals()['TrialDetails'] = TrialDetails
from graalsystems.model.details1 import Details1


class TestDetails1(unittest.TestCase):
    """Details1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetails1(self):
        """Test Details1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Details1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
