"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.data_warehouse import DataWarehouse
globals()['DataWarehouse'] = DataWarehouse
from graalsystems.model.data_warehouse_page_all_of import DataWarehousePageAllOf


class TestDataWarehousePageAllOf(unittest.TestCase):
    """DataWarehousePageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataWarehousePageAllOf(self):
        """Test DataWarehousePageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataWarehousePageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
