"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.resource import Resource
from graalsystems.model.user1_all_of import User1AllOf
globals()['Resource'] = Resource
globals()['User1AllOf'] = User1AllOf
from graalsystems.model.user1 import User1


class TestUser1(unittest.TestCase):
    """User1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUser1(self):
        """Test User1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = User1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
