"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.verification_api import VerificationApi  # noqa: E501


class TestVerificationApi(unittest.TestCase):
    """VerificationApi unit test stubs"""

    def setUp(self):
        self.api = VerificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_verification(self):
        """Test case for create_verification

        Create a verification  # noqa: E501
        """
        pass

    def test_find_verification_by_code(self):
        """Test case for find_verification_by_code

        Find a verification by code  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
