"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.bridge import Bridge
from graalsystems.model.bridge_page_all_of import BridgePageAllOf
from graalsystems.model.page import Page
globals()['Bridge'] = Bridge
globals()['BridgePageAllOf'] = BridgePageAllOf
globals()['Page'] = Page
from graalsystems.model.bridge_page import BridgePage


class TestBridgePage(unittest.TestCase):
    """BridgePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBridgePage(self):
        """Test BridgePage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BridgePage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
