"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.event_hub_notification_all_of import EventHubNotificationAllOf


class TestEventHubNotificationAllOf(unittest.TestCase):
    """EventHubNotificationAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventHubNotificationAllOf(self):
        """Test EventHubNotificationAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventHubNotificationAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
