"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.event_api import EventApi  # noqa: E501


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self):
        self.api = EventApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_event_for_job_and_run(self):
        """Test case for create_event_for_job_and_run

        Add event for a run and a job  # noqa: E501
        """
        pass

    def test_create_event_for_workflow_and_run(self):
        """Test case for create_event_for_workflow_and_run

        Add event for a run and a workflow  # noqa: E501
        """
        pass

    def test_find_events_by_job_id_and_run_id(self):
        """Test case for find_events_by_job_id_and_run_id

        Find the events related to a run  # noqa: E501
        """
        pass

    def test_find_events_by_workflow_id_and_run_id(self):
        """Test case for find_events_by_workflow_id_and_run_id

        Find the events related to a run  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
