"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.usage_api import UsageApi  # noqa: E501


class TestUsageApi(unittest.TestCase):
    """UsageApi unit test stubs"""

    def setUp(self):
        self.api = UsageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_usage(self):
        """Test case for create_usage

        Create an usage  # noqa: E501
        """
        pass

    def test_find_usages(self):
        """Test case for find_usages

        Retrieve all usages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
