"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.details import Details
from graalsystems.model.issue_details import IssueDetails
from graalsystems.model.issue_details_all_of import IssueDetailsAllOf
from graalsystems.model.quota_details import QuotaDetails
from graalsystems.model.subscription_details import SubscriptionDetails
globals()['Details'] = Details
globals()['IssueDetails'] = IssueDetails
globals()['IssueDetailsAllOf'] = IssueDetailsAllOf
globals()['QuotaDetails'] = QuotaDetails
globals()['SubscriptionDetails'] = SubscriptionDetails
from graalsystems.model.issue_details import IssueDetails


class TestIssueDetails(unittest.TestCase):
    """IssueDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueDetails(self):
        """Test IssueDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
