"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.secret import Secret


class TestSecret(unittest.TestCase):
    """Secret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecret(self):
        """Test Secret"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Secret()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
