"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.stream_api import StreamApi  # noqa: E501


class TestStreamApi(unittest.TestCase):
    """StreamApi unit test stubs"""

    def setUp(self):
        self.api = StreamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_stream(self):
        """Test case for create_stream

        Create a stream  # noqa: E501
        """
        pass

    def test_delete_stream_by_id(self):
        """Test case for delete_stream_by_id

        Delete a stream by an id  # noqa: E501
        """
        pass

    def test_find_stream_by_id(self):
        """Test case for find_stream_by_id

        Find stream by Id  # noqa: E501
        """
        pass

    def test_find_streams(self):
        """Test case for find_streams

        Retrieve all streams  # noqa: E501
        """
        pass

    def test_update_stream(self):
        """Test case for update_stream

        Update a stream  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
