"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.notification1 import Notification1


class TestNotification1(unittest.TestCase):
    """Notification1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotification1(self):
        """Test Notification1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Notification1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
