"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.library import Library
globals()['Library'] = Library
from graalsystems.model.spark_options_all_of import SparkOptionsAllOf


class TestSparkOptionsAllOf(unittest.TestCase):
    """SparkOptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSparkOptionsAllOf(self):
        """Test SparkOptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SparkOptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
