"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.s3_uri_all_of import S3UriAllOf


class TestS3UriAllOf(unittest.TestCase):
    """S3UriAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3UriAllOf(self):
        """Test S3UriAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = S3UriAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
