"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.capacity import Capacity


class TestCapacity(unittest.TestCase):
    """Capacity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCapacity(self):
        """Test Capacity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Capacity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
