"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.role_assignment import RoleAssignment


class TestRoleAssignment(unittest.TestCase):
    """RoleAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleAssignment(self):
        """Test RoleAssignment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleAssignment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
