"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.oracle_options_all_of import OracleOptionsAllOf


class TestOracleOptionsAllOf(unittest.TestCase):
    """OracleOptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOracleOptionsAllOf(self):
        """Test OracleOptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OracleOptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
