"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.admin_target import AdminTarget
from graalsystems.model.kubernetes_target import KubernetesTarget
from graalsystems.model.kubernetes_target_all_of import KubernetesTargetAllOf
from graalsystems.model.target import Target
globals()['AdminTarget'] = AdminTarget
globals()['KubernetesTarget'] = KubernetesTarget
globals()['KubernetesTargetAllOf'] = KubernetesTargetAllOf
globals()['Target'] = Target
from graalsystems.model.kubernetes_target import KubernetesTarget


class TestKubernetesTarget(unittest.TestCase):
    """KubernetesTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKubernetesTarget(self):
        """Test KubernetesTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KubernetesTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
