"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.company import Company
from graalsystems.model.contact import Contact
from graalsystems.model.payment_method import PaymentMethod
globals()['Company'] = Company
globals()['Contact'] = Contact
globals()['PaymentMethod'] = PaymentMethod
from graalsystems.model.subscription_details_all_of import SubscriptionDetailsAllOf


class TestSubscriptionDetailsAllOf(unittest.TestCase):
    """SubscriptionDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionDetailsAllOf(self):
        """Test SubscriptionDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubscriptionDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
