"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.azure_log_analytics_notification import AzureLogAnalyticsNotification
from graalsystems.model.event_hub_notification import EventHubNotification
from graalsystems.model.mail_notification import MailNotification
from graalsystems.model.web_hook_notification import WebHookNotification
globals()['AzureLogAnalyticsNotification'] = AzureLogAnalyticsNotification
globals()['EventHubNotification'] = EventHubNotification
globals()['MailNotification'] = MailNotification
globals()['WebHookNotification'] = WebHookNotification
from graalsystems.model.notification import Notification


class TestNotification(unittest.TestCase):
    """Notification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotification(self):
        """Test Notification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Notification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
