"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.mean_params import MeanParams


class TestMeanParams(unittest.TestCase):
    """MeanParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeanParams(self):
        """Test MeanParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MeanParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
