"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.data_warehouse_options import DataWarehouseOptions
globals()['DataWarehouseOptions'] = DataWarehouseOptions
from graalsystems.model.data_warehouse import DataWarehouse


class TestDataWarehouse(unittest.TestCase):
    """DataWarehouse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataWarehouse(self):
        """Test DataWarehouse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataWarehouse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
