"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.graph_api import GraphApi  # noqa: E501


class TestGraphApi(unittest.TestCase):
    """GraphApi unit test stubs"""

    def setUp(self):
        self.api = GraphApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_graph(self):
        """Test case for create_graph

        Create graph  # noqa: E501
        """
        pass

    def test_delete_graph_by_id(self):
        """Test case for delete_graph_by_id

        Delete a graph by an id  # noqa: E501
        """
        pass

    def test_find_graph_by_id(self):
        """Test case for find_graph_by_id

        Find graph by Id  # noqa: E501
        """
        pass

    def test_find_graphs(self):
        """Test case for find_graphs

        Retrieve all graphs  # noqa: E501
        """
        pass

    def test_update_graph(self):
        """Test case for update_graph

        Update a graph  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
