"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.job import Job
from graalsystems.model.job_run import JobRun
globals()['Job'] = Job
globals()['JobRun'] = JobRun
from graalsystems.model.run_with_job import RunWithJob


class TestRunWithJob(unittest.TestCase):
    """RunWithJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunWithJob(self):
        """Test RunWithJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunWithJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
