"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.user1_all_of import User1AllOf


class TestUser1AllOf(unittest.TestCase):
    """User1AllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUser1AllOf(self):
        """Test User1AllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = User1AllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
