"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.firewall_rules_api import FirewallRulesApi  # noqa: E501


class TestFirewallRulesApi(unittest.TestCase):
    """FirewallRulesApi unit test stubs"""

    def setUp(self):
        self.api = FirewallRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_firewall_rule(self):
        """Test case for create_firewall_rule

        Create a firewall rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
