"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.git_library import GitLibrary
globals()['GitLibrary'] = GitLibrary
from graalsystems.model.database_migration_options_all_of import DatabaseMigrationOptionsAllOf


class TestDatabaseMigrationOptionsAllOf(unittest.TestCase):
    """DatabaseMigrationOptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatabaseMigrationOptionsAllOf(self):
        """Test DatabaseMigrationOptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DatabaseMigrationOptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
