"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.patch import Patch


class TestPatch(unittest.TestCase):
    """Patch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatch(self):
        """Test Patch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Patch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
