"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.history_api import HistoryApi  # noqa: E501


class TestHistoryApi(unittest.TestCase):
    """HistoryApi unit test stubs"""

    def setUp(self):
        self.api = HistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_resource_history_for_user(self):
        """Test case for add_resource_history_for_user

        Add history for user  # noqa: E501
        """
        pass

    def test_add_search_history_for_user(self):
        """Test case for add_search_history_for_user

        Add search history for user  # noqa: E501
        """
        pass

    def test_get_resource_history(self):
        """Test case for get_resource_history

        Get resource history for user  # noqa: E501
        """
        pass

    def test_get_search_history(self):
        """Test case for get_search_history

        Search history for user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
