"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.graph import Graph
from graalsystems.model.graph_page_all_of import GraphPageAllOf
from graalsystems.model.page import Page
globals()['Graph'] = Graph
globals()['GraphPageAllOf'] = GraphPageAllOf
globals()['Page'] = Page
from graalsystems.model.graph_page import GraphPage


class TestGraphPage(unittest.TestCase):
    """GraphPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGraphPage(self):
        """Test GraphPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GraphPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
