"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.field_api import FieldApi  # noqa: E501


class TestFieldApi(unittest.TestCase):
    """FieldApi unit test stubs"""

    def setUp(self):
        self.api = FieldApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_field(self):
        """Test case for create_field

        Create a field  # noqa: E501
        """
        pass

    def test_find_fields(self):
        """Test case for find_fields

        Retrieve all fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
