"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.mail_notification_all_of import MailNotificationAllOf


class TestMailNotificationAllOf(unittest.TestCase):
    """MailNotificationAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMailNotificationAllOf(self):
        """Test MailNotificationAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MailNotificationAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
