"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.sepa_details_all_of import SepaDetailsAllOf


class TestSepaDetailsAllOf(unittest.TestCase):
    """SepaDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSepaDetailsAllOf(self):
        """Test SepaDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SepaDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
