"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.xgboost_options_all_of import XgboostOptionsAllOf


class TestXgboostOptionsAllOf(unittest.TestCase):
    """XgboostOptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXgboostOptionsAllOf(self):
        """Test XgboostOptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XgboostOptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
