"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.enrollment import Enrollment
from graalsystems.model.enrollment_page_all_of import EnrollmentPageAllOf
from graalsystems.model.page import Page
globals()['Enrollment'] = Enrollment
globals()['EnrollmentPageAllOf'] = EnrollmentPageAllOf
globals()['Page'] = Page
from graalsystems.model.enrollment_page import EnrollmentPage


class TestEnrollmentPage(unittest.TestCase):
    """EnrollmentPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnrollmentPage(self):
        """Test EnrollmentPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnrollmentPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
