"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.metadata import Metadata
globals()['Metadata'] = Metadata
from graalsystems.model.body_post_template_templates_name_versions_version_post import BodyPostTemplateTemplatesNameVersionsVersionPost


class TestBodyPostTemplateTemplatesNameVersionsVersionPost(unittest.TestCase):
    """BodyPostTemplateTemplatesNameVersionsVersionPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyPostTemplateTemplatesNameVersionsVersionPost(self):
        """Test BodyPostTemplateTemplatesNameVersionsVersionPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyPostTemplateTemplatesNameVersionsVersionPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
