"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.project_api import ProjectApi  # noqa: E501


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_job_for_project(self):
        """Test case for create_job_for_project

        Create job  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create a project  # noqa: E501
        """
        pass

    def test_create_workflow_for_project(self):
        """Test case for create_workflow_for_project

        Create workflows  # noqa: E501
        """
        pass

    def test_delete_project_by_id(self):
        """Test case for delete_project_by_id

        Delete a project by an id  # noqa: E501
        """
        pass

    def test_find_banner_by_project_id(self):
        """Test case for find_banner_by_project_id

        Get banner  # noqa: E501
        """
        pass

    def test_find_jobs_by_project_id(self):
        """Test case for find_jobs_by_project_id

        Retrieve all jobs for a project  # noqa: E501
        """
        pass

    def test_find_latest_runs_by_project_id(self):
        """Test case for find_latest_runs_by_project_id

        Retrieve all jobs for a project  # noqa: E501
        """
        pass

    def test_find_project_by_id(self):
        """Test case for find_project_by_id

        Find project by Id  # noqa: E501
        """
        pass

    def test_find_projects(self):
        """Test case for find_projects

        Retrieve all projects  # noqa: E501
        """
        pass

    def test_find_workflows_by_project_id(self):
        """Test case for find_workflows_by_project_id

        Retrieve all workflows for a project  # noqa: E501
        """
        pass

    def test_get_metrics_for_project(self):
        """Test case for get_metrics_for_project

        Find the metrics for a project  # noqa: E501
        """
        pass

    def test_get_stats_by_project_id(self):
        """Test case for get_stats_by_project_id

        Find the stats for a project  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update a project  # noqa: E501
        """
        pass

    def test_upload_banner(self):
        """Test case for upload_banner

        Upload a new banner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
