"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.page import Page
from graalsystems.model.workspace import Workspace
from graalsystems.model.workspace_page_all_of import WorkspacePageAllOf
globals()['Page'] = Page
globals()['Workspace'] = Workspace
globals()['WorkspacePageAllOf'] = WorkspacePageAllOf
from graalsystems.model.workspace_page import WorkspacePage


class TestWorkspacePage(unittest.TestCase):
    """WorkspacePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspacePage(self):
        """Test WorkspacePage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspacePage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
