"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.details import Details
from graalsystems.model.issue_details import IssueDetails
from graalsystems.model.quota_details import QuotaDetails
from graalsystems.model.quota_details_all_of import QuotaDetailsAllOf
from graalsystems.model.subscription_details import SubscriptionDetails
globals()['Details'] = Details
globals()['IssueDetails'] = IssueDetails
globals()['QuotaDetails'] = QuotaDetails
globals()['QuotaDetailsAllOf'] = QuotaDetailsAllOf
globals()['SubscriptionDetails'] = SubscriptionDetails
from graalsystems.model.quota_details import QuotaDetails


class TestQuotaDetails(unittest.TestCase):
    """QuotaDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuotaDetails(self):
        """Test QuotaDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QuotaDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
