"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.assignment_api import AssignmentApi  # noqa: E501


class TestAssignmentApi(unittest.TestCase):
    """AssignmentApi unit test stubs"""

    def setUp(self):
        self.api = AssignmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_role_assignment(self):
        """Test case for create_role_assignment

        Create a assignment  # noqa: E501
        """
        pass

    def test_delete_role_assignment_by_id(self):
        """Test case for delete_role_assignment_by_id

        Delete an assignment by an id  # noqa: E501
        """
        pass

    def test_find_role_assignment_by_id(self):
        """Test case for find_role_assignment_by_id

        Find assignment by Id  # noqa: E501
        """
        pass

    def test_find_role_assignments(self):
        """Test case for find_role_assignments

        Retrieve all assignments for a resource  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
