"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.company import Company
from graalsystems.model.contact import Contact
from graalsystems.model.details import Details
from graalsystems.model.issue_details import IssueDetails
from graalsystems.model.payment_method import PaymentMethod
from graalsystems.model.quota_details import QuotaDetails
from graalsystems.model.subscription_details import SubscriptionDetails
from graalsystems.model.subscription_details_all_of import SubscriptionDetailsAllOf
globals()['Company'] = Company
globals()['Contact'] = Contact
globals()['Details'] = Details
globals()['IssueDetails'] = IssueDetails
globals()['PaymentMethod'] = PaymentMethod
globals()['QuotaDetails'] = QuotaDetails
globals()['SubscriptionDetails'] = SubscriptionDetails
globals()['SubscriptionDetailsAllOf'] = SubscriptionDetailsAllOf
from graalsystems.model.subscription_details import SubscriptionDetails


class TestSubscriptionDetails(unittest.TestCase):
    """SubscriptionDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionDetails(self):
        """Test SubscriptionDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubscriptionDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
