"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.synapse_options_all_of import SynapseOptionsAllOf


class TestSynapseOptionsAllOf(unittest.TestCase):
    """SynapseOptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSynapseOptionsAllOf(self):
        """Test SynapseOptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SynapseOptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
