"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.project1 import Project1
from graalsystems.model.resource import Resource
from graalsystems.model.workflow1_all_of import Workflow1AllOf
globals()['Project1'] = Project1
globals()['Resource'] = Resource
globals()['Workflow1AllOf'] = Workflow1AllOf
from graalsystems.model.workflow1 import Workflow1


class TestWorkflow1(unittest.TestCase):
    """Workflow1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflow1(self):
        """Test Workflow1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Workflow1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
