"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.bucket_api import BucketApi  # noqa: E501


class TestBucketApi(unittest.TestCase):
    """BucketApi unit test stubs"""

    def setUp(self):
        self.api = BucketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_bucket(self):
        """Test case for create_bucket

        Create a bucket  # noqa: E501
        """
        pass

    def test_delete_bucket_by_id(self):
        """Test case for delete_bucket_by_id

        Delete a bucket by an id  # noqa: E501
        """
        pass

    def test_find_bucket_by_id(self):
        """Test case for find_bucket_by_id

        Find bucket by Id  # noqa: E501
        """
        pass

    def test_find_buckets(self):
        """Test case for find_buckets

        Retrieve all buckets  # noqa: E501
        """
        pass

    def test_update_bucket(self):
        """Test case for update_bucket

        Update a bucket  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
