"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.activity import Activity
from graalsystems.model.project1 import Project1
from graalsystems.model.project_activity_all_of import ProjectActivityAllOf
from graalsystems.model.reaction import Reaction
from graalsystems.model.user1 import User1
globals()['Activity'] = Activity
globals()['Project1'] = Project1
globals()['ProjectActivityAllOf'] = ProjectActivityAllOf
globals()['Reaction'] = Reaction
globals()['User1'] = User1
from graalsystems.model.project_activity import ProjectActivity


class TestProjectActivity(unittest.TestCase):
    """ProjectActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectActivity(self):
        """Test ProjectActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
