"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.byte_capacity import ByteCapacity
from graalsystems.model.capacity import Capacity
globals()['ByteCapacity'] = ByteCapacity
globals()['Capacity'] = Capacity
from graalsystems.model.target_info import TargetInfo


class TestTargetInfo(unittest.TestCase):
    """TargetInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTargetInfo(self):
        """Test TargetInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TargetInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
