"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.action_api import ActionApi  # noqa: E501


class TestActionApi(unittest.TestCase):
    """ActionApi unit test stubs"""

    def setUp(self):
        self.api = ActionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_execute_action(self):
        """Test case for execute_action

        Execute an action  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
