"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.save_model_params import SaveModelParams


class TestSaveModelParams(unittest.TestCase):
    """SaveModelParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveModelParams(self):
        """Test SaveModelParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SaveModelParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
