"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.not_null_filter import NotNullFilter


class TestNotNullFilter(unittest.TestCase):
    """NotNullFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotNullFilter(self):
        """Test NotNullFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotNullFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
