"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.style_api import StyleApi  # noqa: E501


class TestStyleApi(unittest.TestCase):
    """StyleApi unit test stubs"""

    def setUp(self):
        self.api = StyleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_style_by_tenant_id(self):
        """Test case for find_style_by_tenant_id

        Find style by tenant id  # noqa: E501
        """
        pass

    def test_update_style(self):
        """Test case for update_style

        Update the current style  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
