"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.start_task_all_of import StartTaskAllOf


class TestStartTaskAllOf(unittest.TestCase):
    """StartTaskAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStartTaskAllOf(self):
        """Test StartTaskAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StartTaskAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
