"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.tenant_api import TenantApi  # noqa: E501


class TestTenantApi(unittest.TestCase):
    """TenantApi unit test stubs"""

    def setUp(self):
        self.api = TenantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tenant(self):
        """Test case for create_tenant

        Create a tenant  # noqa: E501
        """
        pass

    def test_delete_tenant_by_id(self):
        """Test case for delete_tenant_by_id

        Delete a tenant by its id  # noqa: E501
        """
        pass

    def test_find_realm_by_tenant_id(self):
        """Test case for find_realm_by_tenant_id

        Find realm by tenant id  # noqa: E501
        """
        pass

    def test_find_tenant_by_id(self):
        """Test case for find_tenant_by_id

        Find tenant by Id  # noqa: E501
        """
        pass

    def test_find_tenants(self):
        """Test case for find_tenants

        Retrieve all tenants  # noqa: E501
        """
        pass

    def test_update_tenant(self):
        """Test case for update_tenant

        Update a tenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
