"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.search_history import SearchHistory


class TestSearchHistory(unittest.TestCase):
    """SearchHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchHistory(self):
        """Test SearchHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
