"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.change import Change
from graalsystems.model.change_page_all_of import ChangePageAllOf
from graalsystems.model.page import Page
globals()['Change'] = Change
globals()['ChangePageAllOf'] = ChangePageAllOf
globals()['Page'] = Page
from graalsystems.model.change_page import ChangePage


class TestChangePage(unittest.TestCase):
    """ChangePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangePage(self):
        """Test ChangePage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangePage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
