"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.run_once_schedule_all_of import RunOnceScheduleAllOf


class TestRunOnceScheduleAllOf(unittest.TestCase):
    """RunOnceScheduleAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunOnceScheduleAllOf(self):
        """Test RunOnceScheduleAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunOnceScheduleAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
