"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.activity import Activity
from graalsystems.model.job1 import Job1
from graalsystems.model.job_activity_all_of import JobActivityAllOf
from graalsystems.model.reaction import Reaction
from graalsystems.model.user1 import User1
globals()['Activity'] = Activity
globals()['Job1'] = Job1
globals()['JobActivityAllOf'] = JobActivityAllOf
globals()['Reaction'] = Reaction
globals()['User1'] = User1
from graalsystems.model.job_activity import JobActivity


class TestJobActivity(unittest.TestCase):
    """JobActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobActivity(self):
        """Test JobActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
