"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.infrastructure_api import InfrastructureApi  # noqa: E501


class TestInfrastructureApi(unittest.TestCase):
    """InfrastructureApi unit test stubs"""

    def setUp(self):
        self.api = InfrastructureApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_infrastructure_by_id(self):
        """Test case for delete_infrastructure_by_id

        Delete a infrastructure by an id  # noqa: E501
        """
        pass

    def test_find_capacity_by_infrastructure_by_id(self):
        """Test case for find_capacity_by_infrastructure_by_id

        Retrieve the capacity of an infrastructure  # noqa: E501
        """
        pass

    def test_find_infrastructure_by_infrastructure_id(self):
        """Test case for find_infrastructure_by_infrastructure_id

        Find infrastructure by Id  # noqa: E501
        """
        pass

    def test_find_infrastructures(self):
        """Test case for find_infrastructures

        Retrieve all infrastructure  # noqa: E501
        """
        pass

    def test_find_public_ips_by_infrastructure_id(self):
        """Test case for find_public_ips_by_infrastructure_id

        Find public ips by infrastructure id  # noqa: E501
        """
        pass

    def test_find_services_by_infrastructure_by_id(self):
        """Test case for find_services_by_infrastructure_by_id

        Retrieve the services of an infrastructure  # noqa: E501
        """
        pass

    def test_update_infrastructure(self):
        """Test case for update_infrastructure

        Update an infrastructure  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
