"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.drop_params import DropParams


class TestDropParams(unittest.TestCase):
    """DropParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDropParams(self):
        """Test DropParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DropParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
