"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.azure_log_analytics_notification import AzureLogAnalyticsNotification
from graalsystems.model.azure_log_analytics_notification_all_of import AzureLogAnalyticsNotificationAllOf
from graalsystems.model.event_hub_notification import EventHubNotification
from graalsystems.model.mail_notification import MailNotification
from graalsystems.model.notification import Notification
from graalsystems.model.web_hook_notification import WebHookNotification
globals()['AzureLogAnalyticsNotification'] = AzureLogAnalyticsNotification
globals()['AzureLogAnalyticsNotificationAllOf'] = AzureLogAnalyticsNotificationAllOf
globals()['EventHubNotification'] = EventHubNotification
globals()['MailNotification'] = MailNotification
globals()['Notification'] = Notification
globals()['WebHookNotification'] = WebHookNotification
from graalsystems.model.azure_log_analytics_notification import AzureLogAnalyticsNotification


class TestAzureLogAnalyticsNotification(unittest.TestCase):
    """AzureLogAnalyticsNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureLogAnalyticsNotification(self):
        """Test AzureLogAnalyticsNotification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AzureLogAnalyticsNotification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
