"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.ticket_api import TicketApi  # noqa: E501


class TestTicketApi(unittest.TestCase):
    """TicketApi unit test stubs"""

    def setUp(self):
        self.api = TicketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_ticket(self):
        """Test case for create_ticket

        Create a ticket  # noqa: E501
        """
        pass

    def test_delete_ticket_by_id(self):
        """Test case for delete_ticket_by_id

        Delete a ticket by its id  # noqa: E501
        """
        pass

    def test_execute_action1(self):
        """Test case for execute_action1

        Execute an action  # noqa: E501
        """
        pass

    def test_find_ticket_by_id(self):
        """Test case for find_ticket_by_id

        Find ticket by Id  # noqa: E501
        """
        pass

    def test_find_tickets(self):
        """Test case for find_tickets

        Retrieve all tickets  # noqa: E501
        """
        pass

    def test_update_ticket(self):
        """Test case for update_ticket

        Update a ticket  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
