"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.table1 import Table1


class TestTable1(unittest.TestCase):
    """Table1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTable1(self):
        """Test Table1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Table1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
