"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.paymentmethod_api import PaymentmethodApi  # noqa: E501


class TestPaymentmethodApi(unittest.TestCase):
    """PaymentmethodApi unit test stubs"""

    def setUp(self):
        self.api = PaymentmethodApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_payment_method(self):
        """Test case for create_payment_method

        Create an payment method  # noqa: E501
        """
        pass

    def test_delete_payment_method_by_id(self):
        """Test case for delete_payment_method_by_id

        Delete a payment method by its id  # noqa: E501
        """
        pass

    def test_find_favorite_or_random_valid_payment_method(self):
        """Test case for find_favorite_or_random_valid_payment_method

        Retrieve the favorite payment method and a random valid  # noqa: E501
        """
        pass

    def test_find_payment_method_by_id(self):
        """Test case for find_payment_method_by_id

        Find paymentmethod by Id  # noqa: E501
        """
        pass

    def test_find_payment_methods(self):
        """Test case for find_payment_methods

        Retrieve all payment methods  # noqa: E501
        """
        pass

    def test_update_payment_method(self):
        """Test case for update_payment_method

        Update a payment method  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
