"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.metadata import Metadata
globals()['Metadata'] = Metadata
from graalsystems.model.body_put_template_templates_name_versions_version_put import BodyPutTemplateTemplatesNameVersionsVersionPut


class TestBodyPutTemplateTemplatesNameVersionsVersionPut(unittest.TestCase):
    """BodyPutTemplateTemplatesNameVersionsVersionPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyPutTemplateTemplatesNameVersionsVersionPut(self):
        """Test BodyPutTemplateTemplatesNameVersionsVersionPut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyPutTemplateTemplatesNameVersionsVersionPut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
