"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.cran_library_all_of import CranLibraryAllOf


class TestCranLibraryAllOf(unittest.TestCase):
    """CranLibraryAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCranLibraryAllOf(self):
        """Test CranLibraryAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CranLibraryAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
