"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.cost_api import CostApi  # noqa: E501


class TestCostApi(unittest.TestCase):
    """CostApi unit test stubs"""

    def setUp(self):
        self.api = CostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_costs(self):
        """Test case for get_costs

        Find the costs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
