"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.not_equal_filter import NotEqualFilter


class TestNotEqualFilter(unittest.TestCase):
    """NotEqualFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotEqualFilter(self):
        """Test NotEqualFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotEqualFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
