"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.bridge import Bridge
globals()['Bridge'] = Bridge
from graalsystems.model.bridge_page_all_of import BridgePageAllOf


class TestBridgePageAllOf(unittest.TestCase):
    """BridgePageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBridgePageAllOf(self):
        """Test BridgePageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BridgePageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
