"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.py_pi_library_all_of import PyPiLibraryAllOf


class TestPyPiLibraryAllOf(unittest.TestCase):
    """PyPiLibraryAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPyPiLibraryAllOf(self):
        """Test PyPiLibraryAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PyPiLibraryAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
