"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.tenant1 import Tenant1


class TestTenant1(unittest.TestCase):
    """Tenant1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTenant1(self):
        """Test Tenant1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tenant1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
