"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.admin_target import AdminTarget
from graalsystems.model.kubernetes_target import KubernetesTarget
globals()['AdminTarget'] = AdminTarget
globals()['KubernetesTarget'] = KubernetesTarget
from graalsystems.model.target import Target


class TestTarget(unittest.TestCase):
    """Target unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTarget(self):
        """Test Target"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Target()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
