"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.target import Target
globals()['Target'] = Target
from graalsystems.model.infrastructure import Infrastructure


class TestInfrastructure(unittest.TestCase):
    """Infrastructure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfrastructure(self):
        """Test Infrastructure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Infrastructure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
