"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.endpoint import Endpoint
from graalsystems.model.endpoint_page_all_of import EndpointPageAllOf
from graalsystems.model.page import Page
globals()['Endpoint'] = Endpoint
globals()['EndpointPageAllOf'] = EndpointPageAllOf
globals()['Page'] = Page
from graalsystems.model.endpoint_page import EndpointPage


class TestEndpointPage(unittest.TestCase):
    """EndpointPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointPage(self):
        """Test EndpointPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EndpointPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
