"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.reaction_count import ReactionCount


class TestReactionCount(unittest.TestCase):
    """ReactionCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReactionCount(self):
        """Test ReactionCount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReactionCount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
