"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.azure_connector_options import AzureConnectorOptions


class TestAzureConnectorOptions(unittest.TestCase):
    """AzureConnectorOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureConnectorOptions(self):
        """Test AzureConnectorOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AzureConnectorOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
