"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.table_api import TableApi  # noqa: E501


class TestTableApi(unittest.TestCase):
    """TableApi unit test stubs"""

    def setUp(self):
        self.api = TableApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_table(self):
        """Test case for create_table

        Create a table  # noqa: E501
        """
        pass

    def test_delete_table_by_id(self):
        """Test case for delete_table_by_id

        Delete a table by an id  # noqa: E501
        """
        pass

    def test_find_table_by_id(self):
        """Test case for find_table_by_id

        Find table by Id  # noqa: E501
        """
        pass

    def test_find_tables1(self):
        """Test case for find_tables1

        Retrieve all tables  # noqa: E501
        """
        pass

    def test_update_table(self):
        """Test case for update_table

        Update a table  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
