"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.enrollment import Enrollment
globals()['Enrollment'] = Enrollment
from graalsystems.model.enrollment_page_all_of import EnrollmentPageAllOf


class TestEnrollmentPageAllOf(unittest.TestCase):
    """EnrollmentPageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnrollmentPageAllOf(self):
        """Test EnrollmentPageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnrollmentPageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
