"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.generic_uri_all_of import GenericUriAllOf


class TestGenericUriAllOf(unittest.TestCase):
    """GenericUriAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericUriAllOf(self):
        """Test GenericUriAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenericUriAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
