"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.device_api import DeviceApi  # noqa: E501


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_device(self):
        """Test case for create_device

        Create device  # noqa: E501
        """
        pass

    def test_delete_device_by_id(self):
        """Test case for delete_device_by_id

        Delete a device by an id  # noqa: E501
        """
        pass

    def test_find_device_by_device_id(self):
        """Test case for find_device_by_device_id

        Find device by Id  # noqa: E501
        """
        pass

    def test_find_devices(self):
        """Test case for find_devices

        Retrieve all device  # noqa: E501
        """
        pass

    def test_update_device(self):
        """Test case for update_device

        Update an device  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
