"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.code_api import CodeApi  # noqa: E501


class TestCodeApi(unittest.TestCase):
    """CodeApi unit test stubs"""

    def setUp(self):
        self.api = CodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_code(self):
        """Test case for download_code

        Download code  # noqa: E501
        """
        pass

    def test_verify_code(self):
        """Test case for verify_code

        Verify code  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
