"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.job1 import Job1
from graalsystems.model.user1 import User1
globals()['Job1'] = Job1
globals()['User1'] = User1
from graalsystems.model.job_activity_all_of import JobActivityAllOf


class TestJobActivityAllOf(unittest.TestCase):
    """JobActivityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobActivityAllOf(self):
        """Test JobActivityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobActivityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
