"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.location import Location
from graalsystems.model.user import User
globals()['Location'] = Location
globals()['User'] = User
from graalsystems.model.audit_log import AuditLog


class TestAuditLog(unittest.TestCase):
    """AuditLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuditLog(self):
        """Test AuditLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuditLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
