"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.code_action import CodeAction
from graalsystems.model.dag import Dag
from graalsystems.model.etl_dag_schemas_enums_language_type import EtlDagSchemasEnumsLanguageType
from graalsystems.model.validity_action import ValidityAction
globals()['CodeAction'] = CodeAction
globals()['Dag'] = Dag
globals()['EtlDagSchemasEnumsLanguageType'] = EtlDagSchemasEnumsLanguageType
globals()['ValidityAction'] = ValidityAction
from graalsystems.model.action1 import Action1


class TestAction1(unittest.TestCase):
    """Action1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAction1(self):
        """Test Action1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Action1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
