"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.airflow_options_all_of import AirflowOptionsAllOf


class TestAirflowOptionsAllOf(unittest.TestCase):
    """AirflowOptionsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAirflowOptionsAllOf(self):
        """Test AirflowOptionsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AirflowOptionsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
