"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.workflow_api import WorkflowApi  # noqa: E501


class TestWorkflowApi(unittest.TestCase):
    """WorkflowApi unit test stubs"""

    def setUp(self):
        self.api = WorkflowApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_workflow_by_id(self):
        """Test case for delete_workflow_by_id

        Delete a workflow by its id  # noqa: E501
        """
        pass

    def test_find_run_by_workflow_id_and_run_id(self):
        """Test case for find_run_by_workflow_id_and_run_id

        Find the run by a workflowId and a runId  # noqa: E501
        """
        pass

    def test_find_workflow_by_id(self):
        """Test case for find_workflow_by_id

        Find workflow by Id  # noqa: E501
        """
        pass

    def test_find_workflows(self):
        """Test case for find_workflows

        Retrieve all workflows  # noqa: E501
        """
        pass

    def test_get_stats_by_workflow_id(self):
        """Test case for get_stats_by_workflow_id

        Find the stats for a workflow  # noqa: E501
        """
        pass

    def test_update_workflow(self):
        """Test case for update_workflow

        Update a workflow  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
