"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.s3_connector import S3Connector


class TestS3Connector(unittest.TestCase):
    """S3Connector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3Connector(self):
        """Test S3Connector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = S3Connector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
