"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.request import Request
globals()['Request'] = Request
from graalsystems.model.estimation import Estimation


class TestEstimation(unittest.TestCase):
    """Estimation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEstimation(self):
        """Test Estimation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Estimation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
