"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.services_runtimes import ServicesRuntimes
globals()['ServicesRuntimes'] = ServicesRuntimes
from graalsystems.model.services import Services


class TestServices(unittest.TestCase):
    """Services unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServices(self):
        """Test Services"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Services()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
