"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import graalsystems
from graalsystems.api.catalog_api import CatalogApi  # noqa: E501


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_catalog(self):
        """Test case for update_catalog

        Update catalog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
