"""
    Tenant API

    Tenant API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graalsystems
from graalsystems.model.user1 import User1
globals()['User1'] = User1
from graalsystems.model.user_activity_all_of import UserActivityAllOf


class TestUserActivityAllOf(unittest.TestCase):
    """UserActivityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserActivityAllOf(self):
        """Test UserActivityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserActivityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
